# Generated by Django 5.2 on 2025-05-07 01:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='joined_leagues', to=settings.AUTH_USER_MODEL),
        ),
    ]
