# Generated by Django 5.2 on 2025-04-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_league'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='name',
            new_name='league_name',
        ),
        migrations.RemoveField(
            model_name='league',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='league',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='league',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='league',
            name='league_type',
        ),
        migrations.RemoveField(
            model_name='league',
            name='longitude',
        ),
        migrations.AddField(
            model_name='league',
            name='category',
            field=models.CharField(choices=[('Casual', 'Casual'), ('Competitive', 'Competitive')], default='Casual', max_length=50),
        ),
        migrations.AddField(
            model_name='league',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='sport',
            field=models.CharField(max_length=100),
        ),
    ]
